export {default as Home} from './Home.jsx'
export {default as Exercise} from './Exercise.jsx'
export {default as Tracking} from './Blogs.jsx'
export {default as Login} from './Login.jsx'
export {default as About} from './About.jsx'
export {default as Contact} from './Contact.jsx'
export {default as Welcome} from './Welcome.jsx'
export {default as Dashboard } from './Dashboard.jsx'
export {default as Diagnose } from './Diagnose.jsx'
export {default as ReportViewer } from './ReportViewer.jsx'